# HOMEWORK 1: BASICS PANDAS AND NUMPY

In [2]:
import numpy as np
import pandas as pd

## Question 1
### What's the version of Pandas that you installed?

In [3]:
print(pd.__version__)

1.4.2


### Getting data

In [4]:
# Load data from local machine
df_housing = pd.read_csv('./database/housing.csv')

## Question 2
### How many columns are in the dataset?

In [5]:
print(df_housing.shape[1])


10


## Question 3
### Which columns in the dataset have missing values?

In [6]:
serie_missing = df_housing.isnull().sum(axis = 0)

In [7]:
serie_missing[serie_missing > 0]

total_bedrooms    207
dtype: int64

## Question 4
### How many unique values does the ocean_proximity column have?

In [8]:
df_housing.ocean_proximity.nunique()

5

## Question 5
### What's the average value of the median_house_value for the houses located near the bay?



In [9]:
df_housing[df_housing.ocean_proximity=='NEAR BAY']['median_house_value'].mean()

259212.31179039303

## Question 6
### 1. Calculate the average of total_bedrooms column in the dataset.

In [10]:
avg_bedroom = df_housing.total_bedrooms.mean()

In [11]:
avg_bedroom

537.8705525375618

### 2. Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.

In [12]:
df_housing.total_bedrooms.fillna(avg_bedroom, inplace = True)

In [13]:
df_housing.total_bedrooms.mean()

537.8705525375639

## Question 7

In [14]:
# Select all the options located on islands.
df_island = df_housing[df_housing.ocean_proximity == 'ISLAND']

In [15]:
df_housing.ocean_proximity.unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [16]:
# Select only columns housing_median_age, total_rooms, total_bedrooms.
# Get the underlying NumPy array. Let's call it X.
X = df_island[['housing_median_age', 'total_rooms', 'total_bedrooms']].to_numpy()

In [17]:
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [18]:
XTX = np.dot(X.T, X)

In [19]:
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [20]:
y = np.array([950, 1300, 800, 1000, 1300])
w = np.dot(np.dot(np.linalg.inv(XTX), X.T), y)

In [21]:
print(w)

[23.12330961 -1.48124183  5.69922946]
