In [3]:
# Import package Numpy
import numpy as np

In [4]:
# Creating array
np.array([0,3,5,10])

array([ 0,  3,  5, 10])

## One dimensional arry

In [5]:
np.zeros(4)

array([0., 0., 0., 0.])

In [6]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [7]:
np.full(8, 1.5)

array([1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multidimentional array

In [13]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.array([[2, 3, 4],[4 ,6 ,4], [8, 3, 10]])

array([[ 2,  3,  4],
       [ 4,  6,  4],
       [ 8,  3, 10]])

# Random Generator

In [18]:
np.random.seed(123) # Choose seed for the consistency result between different running
np.random.rand(3,2) 

array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477],
       [0.71946897, 0.42310646]])